[project]
name = "qgis-lobsta"
version = "0.1.0"
description = "QGIS plugin for LOBSTA"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "mypy>=1.15.0",
    "pyright>=1.1.396",
    "ruff>=0.9.10",
]
