[project]
name = "qgis-lobsta"
version = "0.1.0"
description = "QGIS plugin for LOBSTA"
readme = "README.md"
requires-python = ">=3.9"
dependencies = []

[dependency-groups]
dev = [
    "mypy>=1.15.0",
    "types-requests>=2.32.0.20250306",
    "ruff>=0.9.10",
]